package home;

public class HomePageWebElement {

    public static final String searchBoxXPathWebElement = "//*[@id=\"search\"]";
    public static final String textXPATHSWebElement = "//h4[@class='FooterButton__StyledH4-mbwcwk-3 kMXxxr']";
    public static final String calculatorZeroToFifteenXPATHSWebElement = "//*[@id=\"mainContainer\"]/div[4]/div[1]/div/ul/li[1]/a/div[2]";
    public static final String searchHeadphonesXPATHSWebElement = "//a[contains(text(),'Skullcandy Jib Wired Earbuds - Black')]";
    public static final String searchHeadphonesHeartSignXPATHSWebElement = "//span[@class='sc-AxjAm bLenJb']//div[@class='sc-AxiKw eSbheu']//*[local-name()='svg']";
    public static final String calculatorXPATHSWebElement = "//a[contains(text(),'Casio HS8VA Solar Powered Pocket Calculator - Silv')]";
    public static final String addToRegistryXPATHSWebElement = "//*[@id=\"viewport\"]/div[5]/div/div[2]/div[3]/div[2]/div/div/button";
    public static final String deliveryXPATHSWebElement = "//div[contains(text(),'Free Order Pickup')]";
    public static final String registryXPathWebElement = "//*[@id=\"header\"]/div[1]/div[2]/div/div[1]/ul/li[1]/a";
    public static final String registryTextXPathWebElement = "//span[contains(text(),'give the perfect gift')]";
    public static final String weeklyAddXPathXPathWebElement = "//*[@id=\"header\"]/div[1]/div[2]/div/div[1]/ul/li[2]/a";
    public static final String ViewTheWeeklyAdXPathWebElement = "//button[@class='btn btn-primary ng-binding']";
    public static final String addTextXPathWebElement = "//*[@id=\"sectionCarousel\"]/div[3]/span/div/span[2]";
    public static final String loginTextCssSWebElement = "//*[@id=\"root\"]/div/div[1]/div/h2";
    public static final String urlForOffersByCategory = "https://www.target.com/offers/target-circle";
    public static final String addToCartXPathWebElement = "//*[@id=\"cart\"]/span[2]/div";
    public static final String addToCartTextXPathWebElement = "//span[contains(text(),'Have an account? Sign in to see your cart')]";
    public static final String heartButtonXPathWebElement = "//div[@class='h-display-inline-block h-margin-r-tiny']//div[@class='sc-AxhCb eSwYtm']//*[local-name()='svg']";
    public static final String footerLogoXPathWebElement = "//a[@id='footer-logo']";
    public static final String moreXPathWebElement = "//a[@id='more']";
    public static final String targetAppXPathWebElement = "//div[contains(text(),'Target App')]";
    public static final String pharmacyXPathWebElement = "//*[@id=\"more-pharmacy\"]/a/div";
    public static final String whatsNewXPathWebElement = "//div[contains(text(),'s New')]";
    public static final String urlForMoreWhatsNew ="https://www.target.com/finds/gift-ideas";
    public static final String whatsNewTrendsXPathWebElement = "//span[contains(text(),'Trends')]";
    public static final String urlForMoreWhatsNewTrends ="https://www.target.com/finds/gift-ideas";
    public static final String whatsNewSpotLightXPathWebElement = "//span[contains(text(),'Spotlight')]";
    public static final String storeXPathWebElement = "//div[@class='h-text-bold h-text-md']";
    public static final String storeLocationZipcodeXPathWebElement = "//input[@id='zipOrCityState']";
    public static final String searchButtonZipcodeXPathWebElement = "/html/body/div[8]/div/div/div/div/div/div/div/div[1]/div/div[3]/div[2]/button";
    public static final String harlemLocationXPathWebElement = "//h3[contains(text(),'Harlem')]";
    public static final String schoolXPathWebElement = "//div[contains(text(),'Ready for School')]";
    public static final String wifiAndNetworkingXPathWebElement = "//div[contains(text(),'Wi-Fi & Networking')]";
    public static final String wifiAndNetworkingTextXPathWebElement = "//span[contains(text(),'Step up your Wi-Fi')]";
    public static final String wifiAndNetworkingTitle = "Wi-Fi & Networking : Target";
    public static final String sameDayDeliveryXPathWebElement ="//div[contains(text(),'Same Day Delivery with Shipt')]";
    public static final String sharpieXPathWebElement ="//a[contains(text(),'12pk Highlighters Clearview Chisel Tip Multicolor')]";
    public static final String sharpieText ="12pk Highlighters Clearview Chisel Tip Multicolor - Sharpie";
    public static final String sameDayDeliverXPathWebElement ="//button[contains(text(),'Deliver it')]";
    public static final String oderHistoryXPathWebElement ="//span[contains(text(),'Order history')]";
    public static final String kidsHeadPhoneXPathWebElement = "//div[7]//div[1]//div[1]//ul[1]//li[1]//a[1]";
    public static final String jBuddiesHeadPhoneXPathWebElement = "//a[contains(text(),'JBuddies Studio Wired Kids Headphones')]";
    public static final String jBuddiesTitleXPathWebElement = "//span[contains(text(),'JBuddies Studio Wired Kids Headphones')]";
    public static final String listAssistXPathWebElement = "//span[contains(text(),'In just a few simple steps, we')]";
    public static final String freeOrderPickupXPathWebElement ="//div[contains(text(),'Free Order Pickup')]";
    public static final String postItXPathWebElement ="//div[contains(text(),'Post-it')]";
    public static final String postItCurrentUrl = "https://www.target.com/b/post-it/-/N-mqegq";
}